### ISSUE TITLE
trace.Parse error in go1.8.1

### ISSUE THREAD

**Issue by MannyKayy** [divan/gotrace#16]
I followed the advice given in this [issue](https://github.com/divan/gotrace/issues/14)

But get the following error when trying to install the package:
`
./events.go:50: too many arguments in call to trace.Parse
	have (io.Reader, string)
	want (io.Reader)
`

When i attempt to do the same within the docker image provided in this repo,I also get the same error.

Any advice would be greatly appreciated, 
Thanks

**Comment by dnutiu** [comment]
I get

```
panic: not a trace file

goroutine 1 [running]:
main.main()
	/Users/denis/go/src/github.com/divan/gotrace/main.go:39 +0x1f7
```

```go version go1.8 darwin/amd64```

**Comment by 0Animal0** [comment]
not a trace file ,     me too!

**Comment by divan** [comment]
I think I've created a confusion with premature update of docker container.

docker container with gotrace creates trace in Go 1.8 format, but `master` branch of gotrace is expecting Go 1.6 trace format, hence this error.

You may try to use `go18` branch of gotrace, but I have to fix this for sure.
